### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ConsistencyPolicy' Failed to start backend

### ISSUE THREAD

**Issue by myh-st** [bdleavitt/chatgpt-on-azure#36]
### This issue is for a: (mark with an `x`)
```
[x ] bug report -> please search issues before submitting
[ ] feature request (including template changes)
[ ] documentation issue or request
[ ] regression (a behavior that used to work and stopped in a new release)
```

### Description
Please include any relevant information, including repro steps for a bug (with log messages, version, OS, etc..)
>
sh debug.sh

Incomplete environment configuration. These variables are set: AZURE_TENANT_ID
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspaces/chatgpt-on-azure/app/backend/backend_env/lib/python3.9/site-packages/flask/__main__.py", line 3, in <module>
    main()
  File "/workspaces/chatgpt-on-azure/app/backend/backend_env/lib/python3.9/site-packages/flask/cli.py", line 1047, in main
    cli.main()
  File "/workspaces/chatgpt-on-azure/app/backend/backend_env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/workspaces/chatgpt-on-azure/app/backend/backend_env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspaces/chatgpt-on-azure/app/backend/backend_env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/workspaces/chatgpt-on-azure/app/backend/backend_env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/workspaces/chatgpt-on-azure/app/backend/backend_env/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/workspaces/chatgpt-on-azure/app/backend/backend_env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/workspaces/chatgpt-on-azure/app/backend/backend_env/lib/python3.9/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/workspaces/chatgpt-on-azure/app/backend/backend_env/lib/python3.9/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/workspaces/chatgpt-on-azure/app/backend/backend_env/lib/python3.9/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "/workspaces/chatgpt-on-azure/app/backend/backend_env/lib/python3.9/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/workspaces/chatgpt-on-azure/app/backend/app.py", line 95, in <module>
    cosmos_conversation_client = CosmosConversationClient(
  File "/workspaces/chatgpt-on-azure/app/backend/history/cosmosdbservice.py", line 15, in __init__
    self.cosmosdb_client = CosmosClient(self.cosmosdb_endpoint, credential=credential)
  File "/workspaces/chatgpt-on-azure/app/backend/backend_env/lib/python3.9/site-packages/azure/cosmos/cosmos_client.py", line 184, in __init__
    self.client_connection = CosmosClientConnection(
  File "/workspaces/chatgpt-on-azure/app/backend/backend_env/lib/python3.9/site-packages/azure/cosmos/_cosmos_client_connection.py", line 214, in __init__
    self._set_client_consistency_level(database_account, consistency_level)
  File "/workspaces/chatgpt-on-azure/app/backend/backend_env/lib/python3.9/site-packages/azure/cosmos/_cosmos_client_connection.py", line 231, in _set_client_consistency_level
    user_consistency_policy = database_account.ConsistencyPolicy
AttributeError: 'NoneType' object has no attribute 'ConsistencyPolicy'
Failed to start backend

**Comment by myh-st** [comment]
<img width="642" alt="image" src="https://github.com/bdleavitt/chatgpt-on-azure/assets/37788058/d9093722-25cc-4ea3-98c0-44b4f0d97887">


add consistency_level='Session'
